### ISSUE TITLE
Russian ham band plan (HF) 

### ISSUE THREAD

**Issue by levchCode** [miaowware/qrm-resources#29]
[RU.zip](https://github.com/miaowware/qrm-resources/files/5826088/RU.zip)

The plan adapted from Amateur Operator's Union of Russia website: https://srr.ru/radiooperatoram/radiochastoty/

The only issue with it is that I can't properly align some of the tables.

**Comment by classabbyamp** [comment]
is there any chance you can make it a one-page pdf, image, or vector graphic? we can't render html in discord.

**Comment by levchCode** [comment]
[RU.pdf](https://github.com/miaowware/qrm-resources/files/5829748/2.pdf)

How about this?

**Comment by 0x5c** [comment]
Looks good enough 👍 
If you continue working on it, don't hesitate to just post an updated version here.
If this one gets added before, feel free to open a new issue for it

**Comment by classabbyamp** [comment]
@levchCode the band chart has been added, but will not get added to qrm until we convert it to use this repo as a data source (miaowware/qrm2#246)

**Comment by levchCode** [comment]
Ok, in the meantime, I'll try to improve the looks a bit
