### ISSUE TITLE
Bulgaria (LZ) bandchart

### ISSUE THREAD

**Issue by radostin04** [miaowware/qrm-resources#45]
### What would you like to add?

A bandchart for Bulgaria (LZ)

### Is this resource available in a usable format or does it require some work?

I'd say it's ready to use - if any changes are required, you can comment on this issue or email the address on the image and I can implement them

Link: https://cdn.discordapp.com/attachments/778020630524198923/843249194697359380/LZ_Bandchart_-_Final.png

**Comment by classabbyamp** [comment]
> ![image](https://user-images.githubusercontent.com/5366828/118407265-06a34600-b64e-11eb-95fd-56233f9c4c84.png)

that is not necessary. having a similar visual style does not infringe on copyright.

Otherwise, looks pretty good. It'll get added sometime soon.

**Comment by radostin04** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/5366828/118407265-06a34600-b64e-11eb-95fd-56233f9c4c84.png)
> 
> that is not necessary. having a similar visual style does not infringe on copyright.
> 
> Otherwise, looks pretty good. It'll get added sometime soon.

I'm aware that it's not technically copyright infringement, but I decided that it was worth mentioning where I got my inspiration from.

**Comment by posimagi** [comment]
![LZ_Bandchart_-_Updated_2024](https://github.com/miaowware/qrm-resources/assets/1747598/086f6321-166d-4e75-95a4-6bbfc77bf957)

Planning to use this updated image from LZ2CFW.
