### ISSUE TITLE
Map for specific VK Callzones

### ISSUE THREAD

**Issue by m0ze1r** [miaowware/qrm-resources#55]
**What would you like to add?**
_Map of VK Callzones_

**A clear and concise description of what the addition is. Ex. A band chart for** 
_Map of Specific VK callzones_

**Is this resource available in a usable format or does it require some work?**
Yes, Usable Format

**Is the resource be ready for use in qrm?**
_Yes_

**Additional context**

![Au-Callzones](https://gitlab.com/m0ze1r/callsign-rules/-/raw/main/Au-Callzones.png)

**Comment by classabbyamp** [comment]
This is the source, right? https://gitlab.com/m0ze1r/callsign-rules/-/blob/main/Au-Callzones.png

**Comment by 0x5c** [comment]
The image is a picture instead of flat colour shapes, the file size might cause delays when discord accesses it.

The Discord media proxy might also nuke the quality too much on mobile, and might make some elements unreadable.

Could still be a worth a try

**Comment by m0ze1r** [comment]
> This is the source, right? https://gitlab.com/m0ze1r/callsign-rules/-/blob/main/Au-Callzones.png

Correct



> The image is a picture instead of flat colour shapes, the file size might cause delays when discord accesses it.
> 
> The Discord media proxy might also nuke the quality too much on mobile, and might make some elements unreadable.
> 
> Could still be a worth a try

This is how it looks on discord mobile

[https://cdn.discordapp.com/attachments/758971578096287774/932858686756519957/Screenshot_20220118-154625_Discord.jpg](https://cdn.discordapp.com/attachments/758971578096287774/932858686756519957/Screenshot_20220118-154625_Discord.jpg)

**Comment by 0x5c** [comment]
The problem we usually see with the media proxy is for images that are linked to in an embed, like qrm uses. Images that are uploaded by a user/bot as attachments get better quality thumbnails. We'll try it and see how it goes

What attribution do you want for the image? It can be text and URLs, and will be shown in the source section of the embed, like these two links:
![image](https://user-images.githubusercontent.com/5877043/149882978-13a97b5c-ba45-4338-a83e-9629a8bf77f7.png)

**Comment by m0ze1r** [comment]
> The problem we usually see with the media proxy is for images that are linked to in an embed, like qrm uses. Images that are uploaded by a user/bot as attachments get better quality thumbnails. We'll try it and see how it goes

_Interesting, Is there a method where this can be pushed to a test environment before it is pushed to prod so if there are issues I may make adjustments where needed?_


> What attribution do you want for the image? It can be text and URLs, and will be shown in the source section of the embed, like these two links: ![image](https://user-images.githubusercontent.com/5877043/149882978-13a97b5c-ba45-4338-a83e-9629a8bf77f7.png)

**"Australian Callsign Prefixes and Locations 🇦🇺"  
"Source: VK3/VK1TTY"** 

_And the link should point to the /raw/ unless there is another method on which this is done? _
