### ISSUE TITLE
Callsign prefix for Anguilla vp2

### ISSUE THREAD

**Issue by bricktaxonomy** [miaowware/qrm-resources#57]

**Comment by classabbyamp** [comment]
the data comes from [here](https://www.country-files.com/big-cty/), if it's included there but not in the bot, then there's an issue, but otherwise it's something to take up with country-files

**Comment by bricktaxonomy** [comment]
My bad, the correct prefix is vp2e, not vp2. The bot correctly identifies the full prefix.

**Comment by 0x5c** [comment]
To add upon this. the specific database file we use does not contain subdivisions of countries (provinces, states, etc). However, a different file is published by the same person that *does* include subdivisions, the only problem is that it has a different format (it might also not be as complete but I'm not sure about that). We've explored in the past what would be required to use it, and it's a bit more involved than we have time to. We may very well revisit that in the future though.

**Comment by bricktaxonomy** [comment]
My view goes something like this … when I originally queried VP2, I did not realize that VP2 was not definitive for dxcc. Perhaps I should entered the entire callsign instead of what I assumed was a definitive prefix. The error message led me to believe that VP2 was not in the country list. Next time I’ll enter the entire callsign. It would have been handy if QRM merely said ‘not definitive’ and provoked me to enter more/all.
